// <auto-generated />
namespace EnvioEmail.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ativo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ativo));
        
        string IMigrationMetadata.Id
        {
            get { return "202110061209269_Ativo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
